### ISSUE TITLE
Recover Seed - no way to confirm on iPad

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianWallet-iOS#86] opened 2020-08-07 15:32 UTC
In Gordian wallet (Testflight) v.0.1.68 on a IpadOS 13.5.1. and choosing Create Account -> Recover (Testnet bitcoind 0.20.0) lets me input a seed work until the 25th. Then there's no way to confirm this seed.

The back button erases the seed words (if I get back to Recover, the input has gone)

**Comment by Fonta1n3** [comment] 2020-08-08 01:01
@henkvancann Thanks for the issue, this is most likely the exact same bug as what you reported in FN. The issue is Xcode/iOS very recently changed the way they allow alerts to present on iPad's, will get it fixed today.

**Comment by Fonta1n3** [comment] 2020-08-10 08:25
this is fixed as of latest update

**Closed as completed by Fonta1n3** 2020-08-10 08:25 UTC
